# iCCF S2D Preview

Preview how to calculate a CCF from one S2D FITS file using `iccf-make-ccf`, inspect the output FITS, and flatten the CCF into an ML-style row.

In [105]:
from pathlib import Path
import numpy as np
from generate_real_s1d_iccf_dataset import generate_real_s1d_iccf_dataset

In [106]:
from generate_real_s1d_iccf_dataset import (
    collect_input_files,
    build_rvarray,
    calculate_real_s1d_iccf_rows,
    rows_to_dataframe,
    save_real_s1d_iccf_dataset,
    generate_real_s1d_iccf_dataframe,
)

In [126]:
df = generate_real_s1d_iccf_dataframe(
    input_dir="./S1D_spectra/",
    recursive=False,
    pattern="*.fits",
    mask_name="G2",
    mask_instrument="ESPRESSO",
    mask_width=0.5,
    vrad_min=-17.2,
    vrad_max=12.8,
    vrad_step=0.1,
    show_progress=True,
)

df.head()

S1D -> iCCF:   0%|          | 0/7 [00:00<?, ?file/s]

,rv_iccf_mps,fwhm_kms,bis_mps,vspan_mps,wspan_mps,contrast_percent,source_file,source_path,object,date_obs,...,ccf_0291,ccf_0292,ccf_0293,ccf_0294,ccf_0295,ccf_0296,ccf_0297,ccf_0298,ccf_0299,ccf_0300
0,-2564.722496,6.996014,-63.577879,-56.623660,102.538605,56.326757,r.ESPRE.2018-07-09T04:49:52.650_S1D_A.fits,S1D_spectra/r.ESPRE.2018-07-09T04:49:52.650_S1...,vesta,2018-07-09T04:49:52.649,...,6.217607e+07,6.217490e+07,6.217778e+07,6.218036e+07,6.218247e+07,6.218275e+07,6.217850e+07,6.217044e+07,6.216197e+07,6.215364e+07
1,-2564.680448,6.999973,-61.773427,-55.375165,103.600665,56.338339,r.ESPRE.2018-07-09T04:54:31.618_S1D_A.fits,S1D_spectra/r.ESPRE.2018-07-09T04:54:31.618_S1...,vesta,2018-07-09T04:54:31.618,...,6.694027e+07,6.693614e+07,6.692994e+07,6.692073e+07,6.691157e+07,6.690544e+07,6.689924e+07,6.689851e+07,6.690118e+07,6.690786e+07
2,-2568.294462,6.997301,-64.223327,-57.733598,106.086384,56.325113,r.ESPRE.2018-07-09T05:02:16.510_S1D_A.fits,S1D_spectra/r.ESPRE.2018-07-09T05:02:16.510_S1...,vesta,2018-07-09T05:02:16.509,...,5.518799e+07,5.518575e+07,5.518366e+07,5.518001e+07,5.517366e+07,5.516660e+07,5.516172e+07,5.515820e+07,5.515823e+07,5.516113e+07
3,-2567.986400,6.998538,-62.803239,-56.153957,110.296860,56.321472,r.ESPRE.2018-07-09T05:05:24.542_S1D_A.fits,S1D_spectra/r.ESPRE.2018-07-09T05:05:24.542_S1...,vesta,2018-07-09T05:05:24.542,...,5.091786e+07,5.091696e+07,5.091438e+07,5.091206e+07,5.090887e+07,5.090625e+07,5.090507e+07,5.090465e+07,5.090226e+07,5.089937e+07
4,-2566.369011,6.843413,-68.422996,-62.423482,110.021276,57.583724,r.ESPRE.2018-07-09T05:28:23.274_S1D_A.fits,S1D_spectra/r.ESPRE.2018-07-09T05:28:23.274_S1...,vesta,2018-07-09T05:28:23.274,...,1.788984e+08,1.788934e+08,1.788853e+08,1.788761e+08,1.788643e+08,1.788550e+08,1.788459e+08,1.788436e+08,1.788467e+08,1.788501e+08

In [125]:
df.to_csv("./real_s1d_iccf_dataset.csv", index=False)

In [109]:
(-1018.462479 + 224.07597700000002)/1000+15

14.205613498

In [110]:
df.describe()

,rv_iccf_mps,fwhm_kms,bis_mps,vspan_mps,wspan_mps,contrast_percent,mjd_obs,berv_kms,bervmax_kms,n_used_pixels,...,ccf_0291,ccf_0292,ccf_0293,ccf_0294,ccf_0295,ccf_0296,ccf_0297,ccf_0298,ccf_0299,ccf_0300
count,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000e+00,3.000000,...,3.000000e+00,3.000000e+00,3.000000e+00,3.000000e+00,3.000000e+00,3.000000e+00,3.000000e+00,3.000000e+00,3.000000e+00,3.000000e+00
mean,-17114.124887,6.762292,-1473.549187,-1522.971008,6901.607877,58.901706,60785.939813,22.982950,3.017216e+01,440627.333333,...,8.306297e+07,8.306557e+07,8.306747e+07,8.306818e+07,8.306741e+07,8.306610e+07,8.306322e+07,8.306215e+07,8.306044e+07,8.305962e+07
std,13.977833,0.020061,113.188158,119.644953,752.216262,0.079291,12.595490,3.223385,4.347152e-07,1.154701,...,2.215610e+07,2.215862e+07,2.215946e+07,2.215762e+07,2.215593e+07,2.215357e+07,2.215190e+07,2.215175e+07,2.215147e+07,2.215051e+07
min,-17128.107306,6.746015,-1596.428540,-1652.842980,6179.001789,58.810361,60772.329699,19.973835,3.017216e+01,440626.000000,...,5.748939e+07,5.748910e+07,5.748997e+07,5.749267e+07,5.749376e+07,5.749513e+07,5.749417e+07,5.749324e+07,5.749183e+07,5.749204e+07
25%,-17121.111507,6.751086,-1523.550217,-1575.840398,6512.264215,58.876170,60780.316925,21.282101,3.017216e+01,440627.000000,...,7.635855e+07,7.636018e+07,7.636282e+07,7.636616e+07,7.636711e+07,7.636725e+07,7.636508e+07,7.636454e+07,7.636316e+07,7.636376e+07
50%,-17114.115708,6.756157,-1450.671894,-1498.837816,6845.526641,58.941979,60788.304151,22.590368,3.017216e+01,440628.000000,...,9.522770e+07,9.523126e+07,9.523567e+07,9.523966e+07,9.524047e+07,9.523937e+07,9.523600e+07,9.523584e+07,9.523448e+07,9.523548e+07
75%,-17107.133677,6.770430,-1412.109510,-1458.035022,7262.910921,58.947379,60792.744870,24.487507,3.017216e+01,440628.000000,...,9.584976e+07,9.585380e+07,9.585622e+07,9.585594e+07,9.585423e+07,9.585158e+07,9.584775e+07,9.584661e+07,9.584475e+07,9.584340e+07
max,-17100.151645,6.784704,-1373.547126,-1417.232229,7680.295200,58.952778,60797.185588,26.384646,3.017216e+01,440628.000000,...,9.647181e+07,9.647635e+07,9.647678e+07,9.647223e+07,9.646799e+07,9.646380e+07,9.645950e+07,9.645737e+07,9.645501e+07,9.645132e+07

In [111]:

#df = generate_real_s1d_iccf_dataset(
#    input_dir="./S1D_spectra",
#    output_csv="./real_s1d_iccf_dataset.csv",
#)